### ISSUE TITLE
Bug? Maybe?

### ISSUE THREAD

**Issue by aaashleyyyy** [zuzumi-f/Discord-11#11]
What is this thing at the top that says "- New Code" and how do I make it blank instead
![Discord_mxXj5mgylJ](https://user-images.githubusercontent.com/83358470/170584932-cb435eb2-aca6-4820-97e5-1b2a9deee108.png)

**Comment by zuzumi-f** [comment]
it is a watermark because there was two styles
deleted watermark
you can reload and it shloud disappear

**Comment by aaashleyyyy** [comment]
Thank
