### ISSUE TITLE
New server page

### ISSUE THREAD

**Issue by NoAccount1** [zuzumi-f/Discord-11#13]
There is a graphic bug in the create server page 
![image](https://user-images.githubusercontent.com/74969657/187461544-d4505216-22d8-4ca7-8549-06aff0efc8ea.png)

**Comment by zuzumi-f** [comment]
odd, i dont have it
you tried without themes or reloading?
![image](https://user-images.githubusercontent.com/79029257/187471181-b6786500-12e3-4841-a11e-ef6e5c43ef52.png)

**Comment by NoAccount1** [comment]
Yes it is fixed sorry for the disturb
