### ISSUE TITLE
Dropdown for Server Profiles Disappears

### ISSUE THREAD

**Issue by 0xc60f** [zuzumi-f/Discord-11#16]
![image](https://user-images.githubusercontent.com/45770865/198854427-e407d905-dfaf-4166-b5fd-63c31db8847e.png)
The dropdown for the server profiles disappears when this theme is enabled. In addition, the padding around the message is incorrect.

**Comment by zuzumi-f** [comment]
Sorry for the inconvenience, I have been reading similar errors for a few weeks now. Unfortunately, the errors are not replicated in my version, the only thing I could try is for you to inspect the item in your version to see the status of the item.
