### ISSUE TITLE
Gap Between Sidebar and Main Content on Settings Page

### ISSUE THREAD

**Issue by bentuhana** [zuzumi-f/Discord-11#17]
![image](https://user-images.githubusercontent.com/108196023/200683578-71a2162b-807b-4700-b853-bbb4d6b6259b.png)

**Comment by zuzumi-f** [comment]
its the same in windows 11 🤷
![image](https://user-images.githubusercontent.com/79029257/200684914-aa4b5070-3822-486e-9359-3f4527cc3ba3.png)

**Comment by bentuhana** [comment]
Oh, I totally forgot that :D. But when zooming, instead of gaps shrinking, it breaks the visual completely. AFAIK on Windows, making the window smaller shrinks those bars first.

**Comment by zuzumi-f** [comment]
oh that... i'll try to solve it but idk how
