### ISSUE TITLE
Toggle Buttons Not Visible

### ISSUE THREAD

**Issue by UniteTheRed** [zuzumi-f/Discord-11#19]
## The buttons at the voice connected panel are transparent intend of being opaque.

![image](https://user-images.githubusercontent.com/91844316/202593685-f9576b53-ab29-489f-a8b7-5c4c32e3dafa.png)
![image](https://user-images.githubusercontent.com/91844316/202593810-dc2a919f-97e9-4af0-a196-c8bd988ae8e5.png)
![image](https://user-images.githubusercontent.com/91844316/202593839-4aea0f78-a2a5-4949-95ef-b464239881e2.png)
![image](https://user-images.githubusercontent.com/91844316/202593853-2991669a-8a77-4a44-88d9-33672d8d707c.png)

## Switch Buttons and Buttons in general not showing color for being selected.

![image](https://user-images.githubusercontent.com/91844316/202594079-6094925a-d22a-46c7-b0a3-d532a7d18b36.png)

###### Comparison of one switch being toggled and one not.
![image](https://user-images.githubusercontent.com/91844316/202594157-85d27825-261a-42fa-9e56-e0245f1cf92c.png)

## The beta headers not being clear to read.

![image](https://user-images.githubusercontent.com/91844316/202593934-2970ba36-2e54-4232-9d0a-a9e7b44e52bf.png)
![image](https://user-images.githubusercontent.com/91844316/202593943-3d7ada22-748b-4b89-b153-aa847fee74f8.png)

**Comment by zuzumi-f** [comment]
update the theme to version [2.4.0](https://github.com/zuzumi-f/Discord-11/releases/tag/v2.4.0)
