### ISSUE TITLE
Theme broke

### ISSUE THREAD

**Issue by foursplaysroblox** [zuzumi-f/Discord-11#23]
when I right click it the context menu is transparent
![image](https://user-images.githubusercontent.com/82078139/211285013-b260c5ee-fb45-492f-92d1-2f9ad4e77fd8.png)

**Comment by foursplaysroblox** [comment]
looks like I am ignored

**Comment by ajaxnotmeta** [comment]
seems like this theme no longer maintained?

**Comment by zuzumi-f** [comment]
theme working again aaa
