### ISSUE TITLE
[Bug] View As Role

### ISSUE THREAD

**Issue by Shadow514** [zuzumi-f/Discord-11#3]
I don't know if it is one of my themes or plugins but, if not you should probably get it fixed.
Btw if you don't see the problems in the picture, let me know, I will point them out for ya.
![619b29515728b9fdb8e8ebac4c3ff05f](https://user-images.githubusercontent.com/93408587/157995342-c68acff5-cef1-4f92-af5c-f55f0edf4400.png)

**Comment by zuzumi-f** [comment]
![Discord_nIASONeV8w](https://user-images.githubusercontent.com/79029257/157997250-f97be9ec-e875-4a10-aadf-aaf05b48dfb8.png)
reload and should be fixed, this is how it looks now
