### ISSUE TITLE
Theme broke

### ISSUE THREAD

**Issue by nikitaed** [zuzumi-f/Discord-11#35]
Friends list broken
![image](https://github.com/zuzumi-f/Discord-11/assets/74512154/b1cf1076-5f5e-4657-9a81-ab6db56efd1b)

**Comment by zuzumi-f** [comment]
are you sure youre not using the crearts friend grid snippet in your custom css?
it looks like that if i add @import url("https://crearts-community.github.io/Friends-Grid/clients/betterdiscord.css");
but the one i use has no problems
