### ISSUE TITLE
no emoji button in chats

### ISSUE THREAD

**Issue by h4rmy** [zuzumi-f/Discord-11#38]
or make it togglable in theme settings please

**Comment by zuzumi-f** [comment]
dude, i have no idea what are you talking about
![image](https://github.com/zuzumi-f/Discord-11/assets/79029257/ef2d0c97-1afb-46c8-beec-5af9e5c23152)

**Comment by h4rmy** [comment]
![image](https://github.com/zuzumi-f/Discord-11/assets/75831703/ede0bc27-7a8c-4041-8f44-83be0b36a475)
for some reason with this theme i dont have emoji button, i dont have any extensions loaded

**Comment by zuzumi-f** [comment]
you have the removechatbuttons plugin?

**Comment by h4rmy** [comment]
> you have the removechatbuttons plugin?

as I said before, no plugins are running
