### ISSUE TITLE
Enabling glass effect breaks server list

### ISSUE THREAD

**Issue by millionsofplayers** [zuzumi-f/Discord-11#40]
Self explanatory. The glass effect doesn't work either [image](https://files.catbox.moe/qvihee.png)

**Comment by zuzumi-f** [comment]
do you deleted both /**/ and have a custom image?
also if you want to see your desk you need to enable transparency in window settings of betterdiscord
![image](https://github.com/zuzumi-f/Discord-11/assets/79029257/ae8b3715-468e-49b5-bbde-e072cbb8b651)

**Comment by millionsofplayers** [comment]
[Still broken for me, even with the settings on](https://files.catbox.moe/b2egz3.png)
