### ISSUE TITLE
Change Maximize/Minimize icon

### ISSUE THREAD

**Issue by ibnu-ja** [zuzumi-f/Discord-11#41]
Hi. Thank you for the theme.
But I have slight problem with control bar behavior.
When maximized, icon on windows control does not change.

Current behavior:
![gambar](https://github.com/zuzumi-f/Discord-11/assets/10094582/c08e9b58-197c-47bf-a1c8-3cf6f440cec6)

expected:
![gambar](https://github.com/zuzumi-f/Discord-11/assets/10094582/231dea6e-ed2b-46b5-bdde-9768e7ca71b9)

I don't know if this is possible. If not, let us know.

**Comment by zuzumi-f** [comment]
sorry for the delay
i cant change it via css because it doesn't identify whether or not the application is maximized
