### ISSUE TITLE
[Visual bug]Is this the norm?

### ISSUE THREAD

**Issue by bropines** [zuzumi-f/Discord-11#48]
![image](https://github.com/zuzumi-f/Discord-11/assets/57861007/26b67d09-f5d8-49ec-8624-00a4883ac40b)

Or did I break some styles?

**Comment by fearganni** [comment]
Pretty confident something is broken on your side. Maybe you have another theme layered on top?

**Comment by bropines** [comment]
> Pretty confident something is broken on your side. Maybe you have another theme layered on top?

there's a bug related to the plug-in for nitro. I forgot to close the issue because now it doesn't bother anymore.
