### ISSUE TITLE
[Request] User Settings Account Preview

### ISSUE THREAD

**Issue by MintLily** [zuzumi-f/Discord-11#6]
Nitro banners seem a bit too small, in my opinion.

<details>
<summary>Normal</summary>
<img src="https://i.mintlily.lgbt/GqRVQNXCIQuV.png" />
</details>

<details>
<summary>My edits</summary>
<img src="https://i.mintlily.lgbt/OxsFmIn3APEJ.png" />
<code>#app-mount .accountProfileCard-lbN7n- .banner-1YaD3N { height: 200px; }</code><br>
<code>#app-mount .accountProfileCard-lbN7n- .avatar-3mTjvZ { top:  180px; }</code>
</details>

<details>
<summary>Show full banner</summary>
<code>#app-mount .accountProfileCard-lbN7n- .banner-1YaD3N { height: 500px; }</code><br>
<code>#app-mount .accountProfileCard-lbN7n- .avatar-3mTjvZ { top:  480px; }</code>
</details>

<I>Note: I am using Powercord, even though I know this theme is not fully made for Powercord.</i>

**Comment by zuzumi-f** [comment]
The banner is small cause i forgot to background-image: none;
I wanna apply this but only for nitro users so no-nitro users just have the small one
i have no nitro so i cant inspect personal nitro things
can you tell me, is there more elements after .banner-1YaD3N please?

**Comment by MintLily** [comment]
This what i have for mine, with a few extras expanded just in case.
<img src="https://i.mintlily.lgbt/u4Zu9tGEakEJ.png" />

**Comment by MintLily** [comment]
maybe a `#app-mount .accountProfileCard-lbN7n- .banner-1YaD3N[style^="background-image: url("] { /* stuff */ }` can be used for banner detection.

**Comment by zuzumi-f** [comment]
Code applied, this is how should look with nitro now, thx for the idea
![Discord_5rueHLwCCy](https://user-images.githubusercontent.com/79029257/158415849-f2f29197-fb4e-40ff-bdb4-3d4be0fcf0d3.png)
