### ISSUE TITLE
[Request] Add colorblind support for online status

### ISSUE THREAD

**Issue by Dadangdut33** [zuzumi-f/Discord-11#7]
The original discord theme has its own icon depending on each online status and it's very helpful to differentiate them. 
This theme is a little confusing for me as I am partially colorblind. I have to look twice to differentiate between online and idle status.

Original discord
![image](https://user-images.githubusercontent.com/57717531/159847507-845de70a-6cd3-4ea8-85e6-0f8aa792bdd4.png)

Modified theme
![image](https://user-images.githubusercontent.com/57717531/159847797-80da1e19-1901-44a4-99ce-03da5e77e13a.png)

It is easy to differentiate if like this, but hard to differentiate when in guild view, at least for me.

Would be great if the old style is back or maybe add it as an option

**Comment by zuzumi-f** [comment]
The status circle was deleted, now the sapes are normal again
