### ISSUE TITLE
Desktop Background Not Blurry

### ISSUE THREAD

**Issue by zlyfer** [zuzumi-f/Discord-11#8]
I use `--wallpaper-is: none;` and enabled transparency in BD and that worked but I the background is not blurred anymore which ruins the "glass"-effect. When using the provided wallpapaer it works though. Am I missing something or is this intended/not fixable?

Thanks

**Comment by zuzumi-f** [comment]
Is just not possible with BD to have blur in transparency
so yeah, just that
