### ISSUE TITLE
Disable Windows 11 Emojis

### ISSUE THREAD

**Issue by DeMineArchiver** [zuzumi-f/Discord-11#9]
How do I disable Windows 11 emojis? They do not seem to blend in well with the theme at all.

**Comment by zuzumi-f** [comment]
![Discord_eBmbpPTgNs](https://user-images.githubusercontent.com/79029257/164313000-eb7a40c7-4bc1-4ef9-b87c-ccf01510a2e0.png)

you cant, but maybe you can replace them again
